<?php
namespace cmpl\util;


require_once 'PHPUnit/Framework.php';



/**
 * Test class for StringToolkit.
 * Generated by PHPUnit on 2010-06-13 at 14:42:45.
 */
class StringToolkitTest extends \PHPUnit_Framework_TestCase
{
    public function testGetLastToken()
    {
        $this->assertEquals('Baz', StringToolkit::getLastToken('\\', 'foo\bar\Baz'));
    }

    public function testClassnameToPath()
    {
        $path = implode(DIRECTORY_SEPARATOR, array('foo', 'bar', 'Baz'));
        $this->assertEquals($path, StringToolkit::classnameToPath('foo\bar\Baz'));
    }
}
